version: '2'
services:
    db:
        image: postgres:alpine
        ports:
            - "5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/pgdata
    app:
        build: .
        ports:
            - "8080:8080"

    